

version: 2.1 
jobs:
   build:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run build
   test:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: npm install
       - run: npm run test
   hithere:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: echo "Helllooooo!"
workflows:
  version: 2.1
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
            