version: 2.1 
jobs:
   build:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run build
   test:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: 
        command: npm install
        name: Install Packages
       - run: 
        command: npm run test
        name: Run Tests
       - run:
        command: npm run build
        name: Build Static Files
      - persist_to_workspace:
        root: ~/project
        paths:
        - .
   hithere:
     docker:
       - image: cimg/node:21.6.1
     steps:
       - checkout
       - run: echo "Helllooooo!"
workflows:
  # version: 2.1
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
            